import * as React from "react"
import { cva, type VariantProps } from "class-variance-authority"

import { cn } from "@/lib/utils"

/**
 * Generated by `shadcn add alert`, then rebuilt against the Terang Hijau design files.
 * Regenerating this file DISCARDS these edits.
 *
 * One notice shape everywhere: a card with margin and a radius, an icon at 17px, and the
 * text beside it. It is the only thing on a flat page allowed to look like a box, which is
 * what makes it read as an aside rather than as content.
 *
 * Four tones, and they are not interchangeable: `info` explains how the page works,
 * `warning` is waiting on a human, `destructive` is a failure. Do not add a tone without a
 * meaning to go with it, and do not reach for `--live` here — that colour belongs to a
 * running session and nothing else.
 */

const alertVariants = cva(
  "group/alert relative grid gap-0.5 rounded-md border px-3.5 py-3 text-left text-base leading-relaxed has-data-[slot=alert-action]:relative has-data-[slot=alert-action]:pr-18 has-[>svg]:grid-cols-[auto_1fr] has-[>svg]:gap-x-2.5 *:[svg]:row-span-2 *:[svg]:translate-y-0.5 *:[svg]:text-current *:[svg:not([class*='size-'])]:size-[17px]",
  {
    variants: {
      variant: {
        // Neutral. A statement, not a state — the "this answer is an admin summary" note.
        default: "border-border bg-background text-muted-foreground",
        // How this page works, said once: "your question goes straight to the speaker".
        info: "border-accent-border bg-accent text-accent-foreground",
        // Waiting on a human: held for review, unsaved, follow-up needed. Never a failure.
        warning:
          "border-warn-border bg-warn-soft text-warn *:data-[slot=alert-description]:text-warn/90",
        // Something failed. The soft ground and coloured edge are what make it readable
        // as a failure at a glance; the generated default was a plain card.
        destructive:
          "border-destructive-border bg-destructive-soft text-destructive *:data-[slot=alert-description]:text-destructive/90 *:[svg]:text-current",
      },
    },
    defaultVariants: {
      variant: "default",
    },
  }
)

function Alert({
  className,
  variant,
  ...props
}: React.ComponentProps<"div"> & VariantProps<typeof alertVariants>) {
  return (
    <div
      data-slot="alert"
      role="alert"
      className={cn(alertVariants({ variant }), className)}
      {...props}
    />
  )
}

function AlertTitle({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="alert-title"
      className={cn(
        "font-medium group-has-[>svg]/alert:col-start-2 [&_a]:underline [&_a]:underline-offset-3 [&_a]:hover:text-foreground",
        className
      )}
      {...props}
    />
  )
}

function AlertDescription({
  className,
  ...props
}: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="alert-description"
      className={cn(
        "text-sm leading-relaxed text-balance md:text-pretty [&_a]:underline [&_a]:underline-offset-3 [&_a]:hover:text-foreground [&_p:not(:last-child)]:mb-4",
        className
      )}
      {...props}
    />
  )
}

function AlertAction({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="alert-action"
      className={cn("absolute top-2.5 right-3", className)}
      {...props}
    />
  )
}

export { Alert, AlertTitle, AlertDescription, AlertAction }
