"use client"

import * as React from "react"
import { AlertDialog as AlertDialogPrimitive } from "@base-ui/react/alert-dialog"

import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"

/**
 * Generated by `shadcn add alert-dialog`, then edited to the house rules in docs/DESIGN.md.
 * Regenerating this file DISCARDS those edits; re-apply them from that document.
 *
 * What was changed from the generated default, and why:
 *
 *  - `AlertDialogCancel` shipped `size = "default"`, which is not one of this repo's Button
 *    sizes (sm/md/lg/xl/icon). It rendered an unsized button. Now `md`, the 44px floor.
 *  - Backdrop was `bg-black/10` with a blur. Matched to components/admin/Modal.tsx's
 *    `bg-black/50`: this app's one confirmation surface should dim the same amount whichever
 *    of the two it is built on.
 *  - Width. The generated `max-w-xs` is 20rem, which cuts a session's own name in half on a
 *    390px phone. Same shape as Modal instead: the viewport less a gutter, capped at lg.
 *  - `AlertDialogMedia` dropped along with the `has-data-[slot=…]` branches in Header and
 *    Title that only existed to lay it out. No confirmation in this app has an illustration.
 *  - Dark-mode branches removed; there is no dark mode (docs/DESIGN.md § Light only).
 *  - `forceRender` on the backdrop, and z-60 rather than the generated z-50. Both are for the
 *    one confirmation that opens from inside the session drawer. Base UI drops a nested
 *    dialog's backdrop by default, on the assumption the parent already dims the page — but a
 *    drawer dims only the strip of page around itself, at 10%, so the delete confirmation was
 *    floating over a fully lit form. Forcing it back also means it has to out-stack the
 *    drawer's own z-50. Anything this dialog sits over must stay below 60.
 *
 * Dismissal is deliberately not softened: Base UI's alert dialog ignores a backdrop click and
 * Escape by design, and every one of these guards an act with an audience.
 */
function AlertDialog({ ...props }: AlertDialogPrimitive.Root.Props) {
  return <AlertDialogPrimitive.Root data-slot="alert-dialog" {...props} />
}

function AlertDialogTrigger({ ...props }: AlertDialogPrimitive.Trigger.Props) {
  return (
    <AlertDialogPrimitive.Trigger data-slot="alert-dialog-trigger" {...props} />
  )
}

function AlertDialogPortal({ ...props }: AlertDialogPrimitive.Portal.Props) {
  return (
    <AlertDialogPrimitive.Portal data-slot="alert-dialog-portal" {...props} />
  )
}

function AlertDialogOverlay({
  className,
  forceRender = true,
  ...props
}: AlertDialogPrimitive.Backdrop.Props) {
  return (
    <AlertDialogPrimitive.Backdrop
      data-slot="alert-dialog-overlay"
      forceRender={forceRender}
      className={cn(
        "fixed inset-0 isolate z-60 bg-black/50 duration-100 data-open:animate-in data-open:fade-in-0 data-closed:animate-out data-closed:fade-out-0",
        className
      )}
      {...props}
    />
  )
}

function AlertDialogContent({
  className,
  ...props
}: AlertDialogPrimitive.Popup.Props) {
  return (
    <AlertDialogPortal>
      <AlertDialogOverlay />
      <AlertDialogPrimitive.Popup
        data-slot="alert-dialog-content"
        className={cn(
          "fixed top-1/2 left-1/2 z-60 grid w-[calc(100vw-2rem)] max-w-lg -translate-x-1/2 -translate-y-1/2 gap-5 rounded-xl border border-border bg-popover p-5 text-popover-foreground duration-100 outline-none data-open:animate-in data-open:fade-in-0 data-open:zoom-in-95 data-closed:animate-out data-closed:fade-out-0 data-closed:zoom-out-95",
          className
        )}
        {...props}
      />
    </AlertDialogPortal>
  )
}

function AlertDialogHeader({
  className,
  ...props
}: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="alert-dialog-header"
      className={cn("grid gap-1.5", className)}
      {...props}
    />
  )
}

function AlertDialogFooter({
  className,
  ...props
}: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="alert-dialog-footer"
      className={cn("flex flex-col-reverse gap-2.5 sm:flex-row sm:justify-end", className)}
      {...props}
    />
  )
}

function AlertDialogTitle({
  className,
  ...props
}: React.ComponentProps<typeof AlertDialogPrimitive.Title>) {
  return (
    <AlertDialogPrimitive.Title
      data-slot="alert-dialog-title"
      className={cn("text-base font-semibold", className)}
      {...props}
    />
  )
}

function AlertDialogDescription({
  className,
  ...props
}: React.ComponentProps<typeof AlertDialogPrimitive.Description>) {
  return (
    <AlertDialogPrimitive.Description
      data-slot="alert-dialog-description"
      className={cn("text-sm leading-relaxed text-muted-foreground text-pretty", className)}
      {...props}
    />
  )
}

function AlertDialogAction({
  className,
  ...props
}: React.ComponentProps<typeof Button>) {
  return (
    <Button
      data-slot="alert-dialog-action"
      className={cn(className)}
      {...props}
    />
  )
}

function AlertDialogCancel({
  className,
  variant = "outline",
  size = "md",
  ...props
}: AlertDialogPrimitive.Close.Props &
  Pick<React.ComponentProps<typeof Button>, "variant" | "size">) {
  return (
    <AlertDialogPrimitive.Close
      data-slot="alert-dialog-cancel"
      className={cn(className)}
      render={<Button variant={variant} size={size} />}
      {...props}
    />
  )
}

export {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogOverlay,
  AlertDialogPortal,
  AlertDialogTitle,
  AlertDialogTrigger,
}
