"use client"

import { Avatar as AvatarPrimitive } from "@base-ui/react/avatar"

import { cn } from "@/lib/utils"

/**
 * Generated by `shadcn add avatar`, then cut down to the one shape the design uses: a
 * 38px disc holding an initial, on the people list. Regenerating this file DISCARDS
 * these edits — and brings back AvatarGroup, AvatarBadge and the size variants, none of
 * which this product has anywhere to put.
 *
 * There are no uploaded profile pictures in Sual, so `AvatarImage` exists only so the
 * primitive keeps its fallback semantics.
 */
function Avatar({ className, ...props }: AvatarPrimitive.Root.Props) {
  return (
    <AvatarPrimitive.Root
      data-slot="avatar"
      className={cn("relative flex size-9.5 shrink-0 rounded-full select-none", className)}
      {...props}
    />
  )
}

function AvatarImage({ className, ...props }: AvatarPrimitive.Image.Props) {
  return (
    <AvatarPrimitive.Image
      data-slot="avatar-image"
      className={cn("aspect-square size-full rounded-full object-cover", className)}
      {...props}
    />
  )
}

function AvatarFallback({ className, ...props }: AvatarPrimitive.Fallback.Props) {
  return (
    <AvatarPrimitive.Fallback
      data-slot="avatar-fallback"
      className={cn(
        "flex size-full items-center justify-center rounded-full bg-accent text-md font-extrabold text-accent-foreground",
        className
      )}
      {...props}
    />
  )
}

export { Avatar, AvatarImage, AvatarFallback }
