import { mergeProps } from "@base-ui/react/merge-props"
import { useRender } from "@base-ui/react/use-render"
import { cva, type VariantProps } from "class-variance-authority"

import { cn } from "@/lib/utils"

/**
 * Generated by `shadcn add badge`, then rebuilt against the Terang Hijau design files.
 * Regenerating this file DISCARDS these edits.
 *
 * A badge STATES something; it is never tappable. Anything a thumb lands on is a Button —
 * `size="chip"` is the pill that looks like this and behaves like a control.
 *
 * `live` is reserved: a running majelis, and nothing else. It is the only place --live is
 * spent. `secondary`, `ghost` and `link` were dropped — a badge that behaves like a link
 * is a button, and nothing needed the other two.
 *
 * Two axes, so the design's pills don't become a variant each: `variant` is the colour and
 * what it means, `size` is the shape. There are two shapes and no more: a word (30px) and a
 * number (20px square). The design has a word-badge at 30px, 30px and 28px depending on
 * which screen it is on, and an edge on some but not others — that is drift, not intent, so
 * it is one height and always an edge here. The edge matches the tone, so on `live` it is
 * invisible anyway.
 *
 * Not uppercase. The design sets these in sentence case at 11.5px/700 — "Berlangsung",
 * "Rekaman", "Nonaktif" — and Indonesian status labels are long enough already.
 *
 * Fixed `h-5` became `min-h-5.5` so a badge grows with its text rather than clipping it.
 */

const badgeVariants = cva(
  "group/badge inline-flex w-fit shrink-0 items-center justify-center gap-1.5 overflow-hidden rounded-full border font-bold whitespace-nowrap [&>svg]:pointer-events-none [&>svg]:size-3!",
  {
    variants: {
      variant: {
        default: "border-transparent bg-primary text-primary-foreground",
        // A running session. This variant is the ONLY user of --live in the product.
        live: "border-live bg-live text-white",
        // Waiting on a human — a question held for review, a session owing you work.
        warning: "border-warn-border bg-warn-soft text-warn",
        // A green-tinted label on paper: a recording exists, this person is a superadmin.
        accent: "border-accent-border bg-accent text-accent-foreground",
        // A state that needs naming but not attention: closed, finished, deactivated.
        muted: "border-border bg-background text-faint",
        outline: "border-border bg-transparent text-muted-foreground",
        destructive: "border-destructive-border bg-destructive-soft text-destructive",
      },
      size: {
        // The design draws this at 30px in a bar, 30 in a session row and 28 on a person,
        // which is three numbers for one thing. It is 30 everywhere here.
        default: "min-h-[30px] px-3 py-1.5 text-2xs",
        // A number, not a word: the counts in the admin board section headers.
        count: "min-h-5 min-w-5 px-1.5 text-2xs",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

function Badge({
  className,
  variant = "default",
  size = "default",
  render,
  ...props
}: useRender.ComponentProps<"span"> & VariantProps<typeof badgeVariants>) {
  return useRender({
    defaultTagName: "span",
    props: mergeProps<"span">(
      {
        className: cn(badgeVariants({ variant, size }), className),
      },
      props
    ),
    render,
    state: {
      slot: "badge",
      variant,
      size,
    },
  })
}

export { Badge, badgeVariants }
