import { mergeProps } from "@base-ui/react/merge-props"
import { useRender } from "@base-ui/react/use-render"
import { cva, type VariantProps } from "class-variance-authority"

import { cn } from "@/lib/utils"

/**
 * Generated by `shadcn add badge`, then edited to the house rules in docs/DESIGN.md.
 * Regenerating this file DISCARDS those edits; re-apply them from that document.
 *
 * `live` is reserved: a running majelis, and nothing else. It is the only place --live is
 * spent. `secondary`, `ghost` and `link` were dropped — a badge that behaves like a link
 * is a button, and nothing needed the other two.
 *
 * Fixed `h-5` became `min-h-5.5` so a badge grows with its text rather than clipping it;
 * Indonesian status labels ("Berlangsung", "Menunggu review") are longer than the English
 * the default was measured against.
 */

const badgeVariants = cva(
  "group/badge inline-flex min-h-5.5 w-fit shrink-0 items-center justify-center gap-1 overflow-hidden rounded-4xl border border-transparent px-2 py-0.5 text-xs font-medium whitespace-nowrap transition-all focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 has-data-[icon=inline-end]:pr-1.5 has-data-[icon=inline-start]:pl-1.5 aria-invalid:border-destructive aria-invalid:ring-destructive/20 [&>svg]:pointer-events-none [&>svg]:size-3!",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground [a]:hover:opacity-90",
        // A running session. This variant is the ONLY user of --live in the product.
        live: "bg-live font-bold tracking-wide text-white uppercase",
        // Waiting on a human — a question held for review.
        warn: "bg-warn-pill font-bold tracking-wide text-warn uppercase",
        // The quiet default for a state that needs naming but not attention.
        outline: "border-border font-semibold tracking-wide text-muted-foreground uppercase",
        // A green-tinted count or label sitting on paper.
        accent: "bg-accent text-accent-foreground",
        destructive: "bg-destructive-soft text-destructive",
      },
    },
    defaultVariants: {
      variant: "default",
    },
  }
)

function Badge({
  className,
  variant = "default",
  render,
  ...props
}: useRender.ComponentProps<"span"> & VariantProps<typeof badgeVariants>) {
  return useRender({
    defaultTagName: "span",
    props: mergeProps<"span">(
      {
        className: cn(badgeVariants({ variant }), className),
      },
      props
    ),
    render,
    state: {
      slot: "badge",
      variant,
    },
  })
}

export { Badge, badgeVariants }
