import { Button as ButtonPrimitive } from "@base-ui/react/button"
import { cva, type VariantProps } from "class-variance-authority"

import { cn } from "@/lib/utils"

/**
 * Generated by `shadcn add button`, then edited to the house rules in docs/DESIGN.md.
 * Regenerating this file DISCARDS those edits; re-apply them from that document.
 *
 * What was changed from the generated default, and why:
 *
 *  - Sizes. shadcn ships h-8/h-9/h-10 — 32/36/40px, all under the 44px minimum. The jamaah
 *    is on a mosque floor in the evening, on a phone, one-handed, inside a 10–30 minute
 *    window. `sm` is kept at 36px for dense admin rows and is never correct on a public
 *    surface. Sizes xs/icon-xs/icon-sm are dropped; nothing needs them.
 *  - Variants trimmed to the five the app uses. `secondary` is gone: a bordered button on
 *    paper is `outline`.
 *  - `destructive` is an outlined button, not a filled one. Nothing in this product is
 *    destructive enough to earn a solid red block — the system is append-only, so the
 *    worst case is reversible.
 *  - Dark-mode and aria-invalid branches removed; there is no dark mode (docs/DESIGN.md).
 */
const buttonVariants = cva(
  "group/button inline-flex shrink-0 items-center justify-center gap-2 rounded-lg border border-transparent bg-clip-padding text-sm font-semibold whitespace-nowrap transition-colors outline-none select-none focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring disabled:pointer-events-none disabled:opacity-40 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground hover:opacity-90",
        outline: "border-border bg-card hover:border-primary",
        ghost: "hover:bg-muted hover:text-foreground",
        destructive:
          "border-destructive-border text-destructive hover:bg-destructive-soft",
        link: "text-primary underline underline-offset-4 hover:opacity-80",
      },
      size: {
        // 36px. Dense admin rows only — never a control a jamaah touches.
        sm: "min-h-9 px-3 text-sm",
        // 44px. The default, and the floor for every public surface.
        md: "min-h-11 px-4",
        // 48px. Primary call to action.
        lg: "min-h-12 rounded-xl px-5",
        // 52px. The full-width "Ajukan pertanyaan" bar.
        xl: "min-h-13 rounded-xl px-6 text-base font-bold",
        icon: "size-11",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "md",
    },
  }
)

function Button({
  className,
  variant = "default",
  size = "md",
  ...props
}: ButtonPrimitive.Props & VariantProps<typeof buttonVariants>) {
  return (
    <ButtonPrimitive
      data-slot="button"
      className={cn(buttonVariants({ variant, size, className }))}
      {...props}
    />
  )
}

export { Button, buttonVariants }
