import { Button as ButtonPrimitive } from "@base-ui/react/button"
import { cva, type VariantProps } from "class-variance-authority"

import { cn } from "@/lib/utils"

/**
 * Generated by `shadcn add button`, then rebuilt against design/e-terang-hijau.html and
 * design/f-admin-hijau.html. Regenerating this file DISCARDS these edits.
 *
 * The design's one rule: content is flat and full width, controls are rounded. Everything
 * in this file has a radius, so everything in this file is tappable — and nothing without
 * a radius should be reaching for it.
 *
 * The two design files disagree on one name: `.quiet` is the bordered button in the jamaah
 * file and the text-only one in the admin file. The variants below take the meanings, not
 * the names — `outline` is bordered, `ghost` is text-only — so the conflict cannot survive
 * into the app.
 *
 * There is no filled red. The system is append-only, so the worst case is reversible, and
 * `destructive` is an outlined button. For the lighter destructive action the admin file
 * draws as text ("Tarik"), use `ghost` with `text-destructive`.
 *
 * Sizes are the design's tap targets, not shadcn's: the jamaah is on a mosque floor in the
 * evening, one-handed, inside a 10-30 minute window. Nothing here is under 40px.
 */
const buttonVariants = cva(
  "group/button inline-flex shrink-0 items-center justify-center gap-2.5 border-0 font-bold tracking-[-0.01em] whitespace-nowrap transition-colors outline-none select-none focus-visible:outline-3 focus-visible:outline-offset-2 focus-visible:outline-ring disabled:pointer-events-none disabled:opacity-40 [&_svg]:pointer-events-none [&_svg]:shrink-0",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground active:bg-primary-deep",
        // A bordered button on paper. The inset ring keeps the border off the box model,
        // so an outline button and a solid one are the same height to the pixel.
        outline:
          "bg-card text-primary shadow-[inset_0_0_0_1.5px_var(--border)] active:bg-accent",
        // Text only. Sits beside a filled button as the way out of it.
        ghost: "bg-transparent font-semibold text-muted-foreground active:bg-background",
        destructive:
          "bg-card text-destructive shadow-[inset_0_0_0_1.5px_var(--destructive-border)] active:bg-destructive-soft",
        // Waiting on a human, never a failure: deactivating an account, not deleting it.
        warning:
          "bg-card text-warn shadow-[inset_0_0_0_1.5px_var(--warn-border)] active:bg-warn-soft",
        link: "bg-transparent text-primary underline underline-offset-4",
      },
      size: {
        // 42px. Dense admin rows — the actions inside a question card.
        sm: "min-h-[42px] rounded-sm px-3 text-base [&_svg:not([class*='size-'])]:size-[15px]",
        // 48px, the design's --tap. The generic control.
        md: "min-h-12 rounded-md px-4 text-md [&_svg:not([class*='size-'])]:size-4",
        // 54px, full width. The sticky call to action at the foot of a screen.
        lg: "min-h-[54px] w-full rounded-md px-5 text-[calc(15px*var(--step))] [&_svg:not([class*='size-'])]:size-[17px]",
        // 40px pill. Reads as a chip, behaves as a button: the answer timestamps that seek
        // the recording, and the refresh beside a question count. Its edge is PRIMARY, not
        // the grey an `outline` button wears, and that is the whole point — a chip sits in a
        // line of badges that are not tappable, so the green edge is what says this one is.
        // Overrides the variant's edge deliberately; a chip is only ever a chip.
        chip:
          "min-h-10 rounded-full px-3.5 text-sm shadow-[inset_0_0_0_1.5px_var(--primary)] [&_svg:not([class*='size-'])]:size-3",
        icon: "size-12 rounded-full [&_svg:not([class*='size-'])]:size-5",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "md",
    },
  }
)

function Button({
  className,
  variant = "default",
  size = "md",
  render,
  nativeButton,
  ...props
}: ButtonPrimitive.Props & VariantProps<typeof buttonVariants>) {
  return (
    <ButtonPrimitive
      data-slot="button"
      /**
       * Base UI needs to know whether the element it ends up rendering is a real <button>,
       * so it can add the role and keyboard handling itself when it is not. Every `render`
       * in this app hands it a link — "Kirim pertanyaan" that navigates, "Sesi baru", the
       * QR download — so the default follows from that, and it warned loudly in the console
       * until it did. A `render` that really is a native button passes nativeButton itself.
       */
      nativeButton={nativeButton ?? !render}
      render={render}
      className={cn(buttonVariants({ variant, size, className }))}
      {...props}
    />
  )
}

export { Button, buttonVariants }
