"use client"

import { Checkbox as CheckboxPrimitive } from "@base-ui/react/checkbox"
import { CheckIcon } from "lucide-react"

import { cn } from "@/lib/utils"

/**
 * Generated by `shadcn add checkbox`, then rebuilt against the Terang Hijau design files.
 * Regenerating this file DISCARDS these edits.
 *
 * 22px, which is larger than shadcn's 16px default, because both places this appears are
 * one-handed on a phone: the anonymity choice a jamaah makes while asking, and the list of
 * sessions a superadmin assigns to an admin. The dark-mode branches the generator ships
 * were dropped; there is no dark mode.
 */
function Checkbox({ className, ...props }: CheckboxPrimitive.Root.Props) {
  return (
    <CheckboxPrimitive.Root
      data-slot="checkbox"
      className={cn(
        "peer relative flex size-5.5 shrink-0 items-center justify-center rounded-[6px] border-2 border-faint outline-none transition-colors",
        "focus-visible:outline-3 focus-visible:outline-offset-2 focus-visible:outline-ring",
        "disabled:cursor-not-allowed disabled:opacity-50",
        "data-checked:border-primary data-checked:bg-primary data-checked:text-primary-foreground",
        className
      )}
      {...props}
    >
      <CheckboxPrimitive.Indicator
        data-slot="checkbox-indicator"
        className="grid place-content-center text-current [&>svg]:size-3.5 [&>svg]:stroke-3"
      >
        <CheckIcon />
      </CheckboxPrimitive.Indicator>
    </CheckboxPrimitive.Root>
  )
}

export { Checkbox }
