"use client"

import { Collapsible as CollapsiblePrimitive } from "@base-ui/react/collapsible"
import { ChevronDownIcon } from "lucide-react"

import { cn } from "@/lib/utils"

/**
 * Generated by `shadcn add collapsible`, then given the admin board's section header.
 * Regenerating this file DISCARDS these edits.
 *
 * This is what replaced the filter chips. Filtering hides work, so the queue is one list
 * sectioned by what each question needs from you, in that order, with counts in the
 * headers and finished work folded away. A section you can see the size of without
 * opening is the difference between triage and hunting.
 */
function Collapsible({ ...props }: CollapsiblePrimitive.Root.Props) {
  return <CollapsiblePrimitive.Root data-slot="collapsible" {...props} />
}

/**
 * The `.shead` row: a marker icon, the name of the section, its count, and a chevron that
 * points down when open. The whole row is the target.
 */
function CollapsibleTrigger({ className, children, ...props }: CollapsiblePrimitive.Trigger.Props) {
  return (
    <CollapsiblePrimitive.Trigger
      data-slot="collapsible-trigger"
      className={cn(
        "group/collapsible-trigger flex w-full items-center gap-2.5 border-0 bg-transparent px-5 pt-4 pb-2 text-left text-base font-bold text-muted-foreground outline-none focus-visible:outline-3 focus-visible:-outline-offset-3 focus-visible:outline-ring [&_svg]:pointer-events-none [&_svg]:shrink-0",
        className
      )}
      {...props}
    >
      {children}
      <ChevronDownIcon
        aria-hidden
        /* Base UI writes data-panel-open only while open — it never says "false" — so the
           closed state is the default here and open is what removes the rotation. */
        className="ml-auto size-5 -rotate-90 stroke-faint transition-transform duration-200 group-data-[panel-open]/collapsible-trigger:rotate-0 motion-reduce:transition-none"
      />
    </CollapsiblePrimitive.Trigger>
  )
}

function CollapsibleContent({ className, ...props }: CollapsiblePrimitive.Panel.Props) {
  return (
    <CollapsiblePrimitive.Panel
      data-slot="collapsible-content"
      className={cn("flex flex-col gap-3 px-4 pb-1", className)}
      {...props}
    />
  )
}

export { Collapsible, CollapsibleTrigger, CollapsibleContent }
