import * as React from "react"
import { Input as InputPrimitive } from "@base-ui/react/input"

import { cn } from "@/lib/utils"

/**
 * Generated by `shadcn add input`, then edited to the house rules in docs/DESIGN.md.
 * Regenerating this file DISCARDS those edits; re-apply them from that document.
 *
 *  - `h-9` (36px) became `min-h-12` (48px), the design's --tap. The generated height is
 *    below the touch minimum, and this control is on the attendee's submit form.
 *  - A 1.5px border, not 1px: at this size a hairline reads as a disabled field.
 *  - `md:text-sm` dropped. It would shrink the text to 14px on wide viewports; the
 *    `input, textarea, select { font-size: max(1rem, 16px) }` rule in globals.css is
 *    unlayered and overrides it anyway, so the utility was dead code that read as if the
 *    iOS zoom guard could be undercut here.
 *  - Focus is an outline, not a ring, matching every other control in the app.
 *  - `shadow-xs` dropped; the design is flat and border-based, with no shadows anywhere.
 *  - Dark-mode branches dropped. There is no dark mode.
 */
function Input({ className, type, ...props }: React.ComponentProps<"input">) {
  return (
    <InputPrimitive
      type={type}
      data-slot="input"
      className={cn(
        "min-h-12 w-full min-w-0 rounded-sm border-[1.5px] border-input bg-card px-3.5 py-1 text-base transition-colors outline-none file:inline-flex file:h-7 file:border-0 file:bg-transparent file:text-sm file:font-bold file:text-foreground placeholder:text-faint focus-visible:border-ring focus-visible:outline-none disabled:pointer-events-none disabled:cursor-not-allowed disabled:border-border-soft disabled:bg-background disabled:text-faint aria-invalid:border-destructive",
        className
      )}
      {...props}
    />
  )
}

export { Input }
