import * as React from "react"
import { Input as InputPrimitive } from "@base-ui/react/input"

import { cn } from "@/lib/utils"

/**
 * Generated by `shadcn add input`, then edited to the house rules in docs/DESIGN.md.
 * Regenerating this file DISCARDS those edits; re-apply them from that document.
 *
 *  - `h-9` (36px) became `min-h-11` (44px). The generated height is below the touch
 *    minimum, and this control is on the attendee's submit form.
 *  - `md:text-sm` dropped. It would shrink the text to 14px on wide viewports; the
 *    `input, textarea, select { font-size: max(1rem, 16px) }` rule in globals.css is
 *    unlayered and overrides it anyway, so the utility was dead code that read as if the
 *    iOS zoom guard could be undercut here.
 *  - Focus is an outline, not a ring, matching every other control in the app.
 *  - `shadow-xs` dropped; the design is flat and border-based, with no shadows anywhere.
 *  - Dark-mode branches dropped. There is no dark mode.
 */
function Input({ className, type, ...props }: React.ComponentProps<"input">) {
  return (
    <InputPrimitive
      type={type}
      data-slot="input"
      className={cn(
        "min-h-11 w-full min-w-0 rounded-lg border border-input bg-transparent px-3 py-1 text-base transition-colors outline-none file:inline-flex file:h-7 file:border-0 file:bg-transparent file:text-sm file:font-medium file:text-foreground placeholder:text-faint focus-visible:border-ring focus-visible:outline-2 focus-visible:outline-offset-0 focus-visible:outline-ring disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive aria-invalid:outline-destructive",
        className
      )}
      {...props}
    />
  )
}

export { Input }
