import * as React from "react"

import { cn } from "@/lib/utils"

/**
 * Generated by `shadcn add textarea`, then edited to the house rules in docs/DESIGN.md.
 * Regenerating this file DISCARDS those edits; re-apply them from that document.
 *
 * Same edits as components/ui/input.tsx: no `md:text-sm`, no dark-mode branches, a 1.5px
 * border. Focus is the one place this control differs from Input — a green halo as well
 * as a green edge, because the question box is the thing on the page you are meant to be
 * typing into, and it is usually the only one.
 *
 * `min-h-16` is the floor; the ask screen sets 150px and the admin's answer box 110px.
 *
 * One family throughout, so a jamaah's question and an admin's answer box are the same
 * face; a question earns its emphasis from size and weight instead (see --text-* in
 * globals.css).
 */
function Textarea({ className, ...props }: React.ComponentProps<"textarea">) {
  return (
    <textarea
      data-slot="textarea"
      className={cn(
        "flex field-sizing-content min-h-16 w-full rounded-md border-[1.5px] border-input bg-card px-3.5 py-3 text-base leading-relaxed transition-[color,border-color,box-shadow] outline-none placeholder:text-faint focus-visible:border-ring focus-visible:shadow-[0_0_0_3px_color-mix(in_oklab,var(--ring)_16%,transparent)] focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive",
        className
      )}
      {...props}
    />
  )
}

export { Textarea }
