import * as React from "react"

import { cn } from "@/lib/utils"

/**
 * Generated by `shadcn add textarea`, then edited to the house rules in docs/DESIGN.md.
 * Regenerating this file DISCARDS those edits; re-apply them from that document.
 *
 * Same edits as components/ui/input.tsx: no `md:text-sm`, outline focus rather than a
 * ring, no shadow, no dark-mode branches. Height is left at the generated `min-h-16`,
 * which is already well over the touch minimum.
 *
 * The question box in AskDrawer passes `font-serif` — a question is reading matter, not
 * interface chrome (docs/DESIGN.md § Type). The default here stays sans for the admin's
 * answer box.
 */
function Textarea({ className, ...props }: React.ComponentProps<"textarea">) {
  return (
    <textarea
      data-slot="textarea"
      className={cn(
        "flex field-sizing-content min-h-16 w-full rounded-lg border border-input bg-transparent px-3 py-2 text-base leading-relaxed transition-colors outline-none placeholder:text-faint focus-visible:border-ring focus-visible:outline-2 focus-visible:outline-offset-0 focus-visible:outline-ring disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive aria-invalid:outline-destructive",
        className
      )}
      {...props}
    />
  )
}

export { Textarea }
