"use client"

import { Toggle as TogglePrimitive } from "@base-ui/react/toggle"
import { cva, type VariantProps } from "class-variance-authority"

import { cn } from "@/lib/utils"

/**
 * Generated by `shadcn add toggle`, then rebuilt against design/f-admin-hijau.html.
 * Regenerating this file DISCARDS these edits.
 *
 * The two controls that change mid-session sit on the board itself, not behind a
 * settings sheet. A toggle that only highlights is a toggle whose meaning you have to
 * remember, so these state what they currently are and change words when tapped: pass
 * both labels as <ToggleOn> and <ToggleOff> and exactly one renders.
 *
 * `warning` is for a state that means work is queuing up for a human ("Review dulu"),
 * which is amber everywhere else in the product too.
 */
const toggleVariants = cva(
  "group/toggle inline-flex min-h-9.5 shrink-0 items-center gap-1.5 rounded-full border px-3.5 text-sm font-semibold whitespace-nowrap transition-colors outline-none focus-visible:outline-3 focus-visible:outline-offset-2 focus-visible:outline-ring disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-3.5",
  {
    variants: {
      variant: {
        default:
          "border-border bg-card text-muted-foreground aria-pressed:border-accent-border aria-pressed:bg-accent aria-pressed:font-bold aria-pressed:text-primary",
        warning:
          "border-border bg-card text-muted-foreground aria-pressed:border-warn-border aria-pressed:bg-warn-pill aria-pressed:font-bold aria-pressed:text-warn",
      },
    },
    defaultVariants: {
      variant: "default",
    },
  }
)

function Toggle({
  className,
  variant = "default",
  ...props
}: TogglePrimitive.Props & VariantProps<typeof toggleVariants>) {
  return (
    <TogglePrimitive
      data-slot="toggle"
      className={cn(toggleVariants({ variant, className }))}
      {...props}
    />
  )
}

/** Shown while the toggle is on. Hidden, not unmounted, so the width never jumps. */
function ToggleOn({ className, ...props }: React.ComponentProps<"span">) {
  return (
    <span
      data-slot="toggle-on"
      className={cn(
        "inline-flex items-center gap-1.5 group-aria-[pressed=false]/toggle:hidden",
        className
      )}
      {...props}
    />
  )
}

function ToggleOff({ className, ...props }: React.ComponentProps<"span">) {
  return (
    <span
      data-slot="toggle-off"
      className={cn(
        "inline-flex items-center gap-1.5 group-aria-[pressed=true]/toggle:hidden",
        className
      )}
      {...props}
    />
  )
}

export { Toggle, ToggleOn, ToggleOff, toggleVariants }
